// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/rmonroy-wiz/ondemand-go-bootcamp-2022/model"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ExternalPokemonAPIMock is an autogenerated mock type for the ExternalPokemonAPI type
type ExternalPokemonAPIMock struct {
	mock.Mock
}

// GetPokemonFromAPI provides a mock function with given fields: id
func (_m *ExternalPokemonAPIMock) GetPokemonFromAPI(id int) (*model.PokemonAPI, *model.ErrorHandler) {
	ret := _m.Called(id)

	var r0 *model.PokemonAPI
	if rf, ok := ret.Get(0).(func(int) *model.PokemonAPI); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PokemonAPI)
		}
	}

	var r1 *model.ErrorHandler
	if rf, ok := ret.Get(1).(func(int) *model.ErrorHandler); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorHandler)
		}
	}

	return r0, r1
}

// NewExternalPokemonAPIMock creates a new instance of ExternalPokemonAPIMock. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewExternalPokemonAPIMock(t testing.TB) *ExternalPokemonAPIMock {
	mock := &ExternalPokemonAPIMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
